In [4]:
#find max element in numpy array
import numpy as np
m=0
ar=np.array([5,6,4,81,111,7])
for i in ar:
    if m<i:
        m=i
print("max element is:-",m)
    

max element is:- 111


In [12]:
#WAP to sort the elements of the NumPy array?
import numpy as np
ar=np.array([5,9,6,2,8,95,62,32,45])
for i in range(0,len(ar)):
    for j in range(i+1,len(ar)):
        if ar[i]>ar[j]:
            ar[i],ar[j]=ar[j],ar[i]
print(ar)

[ 2  5  6  8  9 32 45 62 95]


In [15]:
#WAP to split one array into two different subarrays?
import numpy as np
ar=np.array([1,9,6,5,8,4,6,3,2,8,5,7,4])
a=ar[0:int(len(ar)/2)]
b=ar[int(len(ar)/2):len(ar)]
print(a)
print(b)


[1 9 6 5 8 4]
[6 3 2 8 5 7 4]


In [24]:
#WAP to merge two NumPy arrays into one array
import numpy as np
ar1=np.array([1,7,3,9,3,5,6,7])
ar2=np.array([4,65,4,32,5,6,7])
ar3=np.concatenate((ar1,ar2))
print(ar3)

[ 1  7  3  9  3  5  6  7  4 65  4 32  5  6  7]


In [30]:
#WAP to display prime elements in Numpy array
import numpy as np
ar=np.array([4,9,6,3,7,8,5,1,2])
for i in range(0,len(ar)):
    if ar[i]>=2:
        for j in range(2,ar[i]):
            if (ar[i]%j)==0:
                break
        else:
            print(ar[i])

3
7
5
2
