In [1]:
import numpy as np

In [2]:
#Find the minimum and maximum element in an array
l=[]
n=int(input("enter the length of array:="))
for i in range(0,n):
    num=int(input("enter the elements:-"))
    l.append(num)
    arr=np.array(l)
m=arr[0]
mi=arr[0]
for i in range(0,n):
    
    if arr[i]>m:
        m=arr[i]
for i in range(0,n):
    
    if arr[i]<mi:
        mi=arr[i]
print("max  is:-",m,"min is:-",mi)


enter the length of array:=1
enter the elements:-1
max  is:- 1 min is:- 1


In [3]:
#Write a program to reverse the array

arr=np.array([1,2,3,6,59,8,2,3,6])
for i in range(len(arr)-1,-1,-1):
    print(arr[i])
type(arr)

6
3
2
8
59
6
3
2
1


numpy.ndarray

In [4]:
#Write a program to sort the given array
arr=np.array([1,9,6,3,85,96,32,321])
for i in range(0,len(arr)):
    for j in range(0,len(arr)):
        if arr[i]<arr[j]:
            arr[i],arr[j]=arr[j],arr[i]
arr
            

array([  1,   3,   6,   9,  32,  85,  96, 321])

In [21]:
#Find the Kth largest and Kth smallest number in an array
arr=np.array([1,9,6,3,7,5,3,4,12,36,98,74,52,20,30,98])
for i in range(0,len(arr)):
    for j in range(0,len(arr)):
        if arr[i]<arr[j]:
            arr[i],arr[j]=arr[j],arr[i]
small=int(input("smallest number"))
print(arr[small-1])
large=int(input("largest number"))
print(arr[-large])


smallest number1
1
largest number1
98


In [6]:
#Find the occurrence of an integer in the array
l=[]
num=int(input("enter number:-"))
while num>0:
    a=num%10
    l.append(a)
    arr=np.array(l)
    num=num//10
for i in range(0,10):
    count=0
    for j in range(0,len(arr)):
        if i==arr[j]:
            count+=1
    print("number     ",i,"     repeated    ",count)

enter number:-1
number      0      repeated     0
number      1      repeated     1
number      2      repeated     0
number      3      repeated     0
number      4      repeated     0
number      5      repeated     0
number      6      repeated     0
number      7      repeated     0
number      8      repeated     0
number      9      repeated     0


In [7]:
#Sort the array of 0s, 1s, and 2s
arr=np.array([1,0,2,0,1,0,2,0,1,2,2,2,0,1,0,2,0,1,0,2])
low=0
mid=0
high=len(arr)-1
while mid<=high:
    if arr[mid]==0:
        arr[low],arr[mid]=arr[mid],arr[low]
        mid+=1
        low+=1
    elif arr[mid]==1:
        mid+=1
    else:
        arr[high],arr[mid]=arr[mid],arr[high]
        high-=1
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [8]:
#Range and Coefficient of array
arr=np.array([5,10,9,6,8,12,15])
mx=arr[0]
mn=arr[0]
for i in range(0,len(arr)):
    if arr[i]>mx:
        mx=arr[i]
    if arr[i]<mn:
        mn=arr[i]
r=mx-mn
print("range of array is:-",r)
r1=mx+mn
c=r/r1
print("coefficient of array is:-",c)

range of array is:- 10
coefficient of array is:- 0.5


In [9]:
#Move all the negative elements to one side of the array
arr=np.array([9,6,3,-8,-1,-7,-6,-4,10])
j=0
for i in range(0,len(arr)):
    if arr[i]<0:
            arr[i],arr[j]=arr[j],arr[i]
            j+=1
arr

array([-8, -1, -7, -6, -4,  3,  9,  6, 10])

In [10]:
#Find the Union and Intersection of the two sorted arrays
arr1=np.array([1,3,4,6,8,9])
arr2=np.array([4,6,7,9,10,15])
size=len(arr1)+len(arr2)
arr3=np.array([int]*size)
s=[]
for i in range(0,size):
    if i<len(arr1):
        arr3[i]=arr1[i]
    else:
        arr3[i]=arr2[i-len(arr1)]
a=set(arr3)
m=np.array([a])
print("union is:-",m)
for i in range(0,len(arr1)):
    for j in range(0,len(arr2)):
        if arr1[i]==arr2[j]:
            s.append(arr1[i])
print("intersection is:-",np.array(s))
    


union is:- [{1, 3, 4, 6, 7, 8, 9, 10, 15}]
intersection is:- [4 6 9]


In [11]:
#Write a program to cyclically rotate an array by one
arr=np.array([1,5,9,3,5,9,6,2,6,8,4,14,5])
j=0
for i in range(0,len(arr)):
      arr[i],arr[j]=arr[j],arr[i]
arr


array([ 5,  1,  5,  9,  3,  5,  9,  6,  2,  6,  8,  4, 14])

In [12]:
#Find the missing integer
arr=np.array([1,9,6,3,7,15,5])
mx=arr[0]
mn=arr[0]
for i in range(0,len(arr)):
    if arr[i]>mx:
        mx=arr[i]
    if arr[i]<mn:
        mn=arr[i]
for i in range(mn,mx):
    if i not in arr:
        print(i)
        


2
4
8
10
11
12
13
14


In [13]:
#Count Pairs with given sum
arr=np.array([1, 5, 7, -1, 5])
sum=6
count=0
for i in range(0,len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]+arr[j]==sum:
            count+=1
print(count)

3


In [14]:
#Find duplicates in an array
arr=np.array([1,1,2,2,5,9,6,6,3,4,7,8,5,-1,-1,-9876,-9876])
for i in range(0,len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]==arr[j]:
            print(arr[i])

1
2
5
6
-1
-9876
